VERSION="2.0.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

[[CURRENCIES]]
script="CDW3T2DXLNGMQDZLMINEF3QHXYDB3F4ZJOGQSKW6QYABA4HMUFRG7DXC"
code="PHASER_LIQ"
name="Phase Liquidity"
desc="PHASER_LIQ utility liquidity token for PHASE settlement flows."
image="/phaser-liq-token.png"
display_decimals=7
