VERSION="2.0.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

[[CURRENCIES]]
code="PHASERLIQ"
issuer="GAXRPE5JXPY7RJONMCEWFXELVWDW3CSA7H6LAGYKTOYLFQQDJ5DT4GNS"
script="CDOAXHWC6YJB7U3ELV67HKJY6HEMJFBNRGJK6WZGUAELBWP3WP77RLFD"
name="Phase Liquidity"
desc="PHASERLIQ utility liquidity token for PHASE settlement flows."
image="https://www.phasee.xyz/phaser-liq-token.png"
display_decimals=7
