/**
 * POST /api/agent/forge
 *
 * Autonomous x402 forge endpoint for AI agents. Handles the full payment +
 * generation cycle in a single HTTP call — no human wallet, no Freighter.
 *
 * Auth: Authorization: Bearer <AGENT_API_KEY>
 * Body: { prompt: string, payerAddress?: string, lang?: "en" | "es" }
 *
 * Flow:
 *   1. Verify bearer token against AGENT_API_KEY
 *   2. POST to /api/forge-agent without payment → receive 402 + challenge
 *   3. Sign + submit PHASELQ settle tx using AGENT_STELLAR_SECRET_KEY
 *   4. Re-POST to /api/forge-agent with settlementTxHash + payerAddress
 *   5. Upload generated image to IPFS (if PINATA_JWT configured)
 *   6. Return enriched response: payer, amountPaid, txHash, tokenId, ipfsCid, collectionId
 */

import { NextRequest, NextResponse } from "next/server"
import { Keypair } from "@stellar/stellar-sdk"
import { settleX402Challenge, type X402Challenge } from "@/lib/x402-agent-client"
import { PHASER_LIQ_SYMBOL, REQUIRED_AMOUNT, stroopsToLiqDisplay } from "@/lib/phase-protocol"

export const runtime = "nodejs"
export const maxDuration = 180
export const dynamic = "force-dynamic"

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type AgentForgeBody = {
  prompt?: string
  payerAddress?: string
  /** Lore language: `en` (default) | `es`. */
  lang?: string
}

type AgentForgeSuccessResponse = {
  success: true
  /** Address that paid (agent wallet). */
  payer: string
  /** Human-readable amount paid, e.g. "1.00 PHASELQ". */
  amountPaid: string
  /** Stellar transaction hash of the confirmed settle payment. */
  txHash: string
  /** Generated image URL (data URL from Gemini, or Pollinations URL as fallback). */
  imageUrl: string
  /** Lore text generated by Gemini. */
  lore: string
  /** IPFS CID of the uploaded image, or null if PINATA_JWT is not configured. */
  ipfsCid: string | null
  /**
   * Token ID is not assigned until a full on-chain mint is triggered. This
   * endpoint generates the artifact and uploads it; the on-chain mint step is
   * separate. Included as null so callers can extend the flow later.
   */
  tokenId: number | null
  collectionId: number
}

type AgentForgeErrorResponse = {
  success: false
  error: string
  detail?: string
}

type AgentForgeResponse = AgentForgeSuccessResponse | AgentForgeErrorResponse

// ---------------------------------------------------------------------------
// Env helpers
// ---------------------------------------------------------------------------

function agentApiKey(): string | null {
  return process.env.AGENT_API_KEY?.trim() || null
}

function agentStellarSecretKey(): string | null {
  return process.env.AGENT_STELLAR_SECRET_KEY?.trim() || null
}

function pinataJwt(): string | null {
  return (process.env.PINATA_JWT ?? process.env.PINATA_API_JWT)?.trim() || null
}

// ---------------------------------------------------------------------------
// Bearer auth
// ---------------------------------------------------------------------------

function verifyBearerToken(authHeader: string | null): boolean {
  const key = agentApiKey()
  if (!key) return false
  if (!authHeader?.toLowerCase().startsWith("bearer ")) return false
  const token = authHeader.slice(7).trim()
  return token === key
}

function normalizeAgentForgeLang(raw: unknown): "en" | "es" {
  if (typeof raw !== "string") return "en"
  const v = raw.trim().toLowerCase()
  if (v === "es" || v === "spa" || v === "spanish") return "es"
  return "en"
}

// ---------------------------------------------------------------------------
// Challenge extraction from 402 response
// ---------------------------------------------------------------------------

type ForgeAgentPaymentRequiredBody = {
  challenge?: Partial<X402Challenge>
  paymentRequirements?: unknown
}

function extractChallengeFrom402(body: ForgeAgentPaymentRequiredBody): X402Challenge | null {
  const c = body.challenge
  if (!c) return null
  if (
    typeof c.protocol !== "string" ||
    typeof c.network !== "string" ||
    typeof c.amount !== "number" ||
    typeof c.token !== "string" ||
    typeof c.facilitator !== "string" ||
    typeof c.invoice !== "string"
  ) {
    return null
  }
  return c as X402Challenge
}

// ---------------------------------------------------------------------------
// IPFS upload
// ---------------------------------------------------------------------------

/**
 * Uploads an image (data URL or remote URL) to IPFS via Pinata.
 * Returns the CID string on success, null if Pinata is not configured or the
 * upload fails (non-fatal — generation still returns successfully).
 */
async function uploadImageToIpfs(imageUrl: string): Promise<string | null> {
  const jwt = pinataJwt()
  if (!jwt) return null

  try {
    let blob: Blob

    if (imageUrl.startsWith("data:")) {
      // data URL — convert base64 to binary
      const [header, b64] = imageUrl.split(",")
      if (!header || !b64) return null
      const mimeMatch = header.match(/data:([^;]+)/)
      const mime = mimeMatch?.[1] ?? "image/png"
      const binary = Buffer.from(b64, "base64")
      blob = new Blob([binary], { type: mime })
    } else {
      // Remote URL (Pollinations etc.) — fetch and forward
      const res = await fetch(imageUrl, { cache: "no-store" })
      if (!res.ok) return null
      blob = await res.blob()
    }

    const form = new FormData()
    form.append("file", blob, "phase-artifact.png")

    const pinRes = await fetch("https://api.pinata.cloud/pinning/pinFileToIPFS", {
      method: "POST",
      headers: { Authorization: `Bearer ${jwt}` },
      body: form,
    })

    if (!pinRes.ok) return null
    const data = (await pinRes.json()) as { IpfsHash?: string }
    return data.IpfsHash ?? null
  } catch {
    return null
  }
}

// ---------------------------------------------------------------------------
// Inner forge call (reuses /api/forge-agent logic)
// ---------------------------------------------------------------------------

type ForgeAgentSuccessBody = {
  success: true
  imageUrl?: string
  image_url?: string
  lore?: string
}

/**
 * Calls /api/forge-agent with the settlement proof.
 * Returns the raw forge-agent success body or throws.
 */
async function callForgeAgentWithProof(
  origin: string,
  prompt: string,
  settlementTxHash: string,
  payerAddress: string,
  lang: "en" | "es",
): Promise<ForgeAgentSuccessBody> {
  const forgeUrl = `${origin}/api/forge-agent`
  const res = await fetch(forgeUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settlementTxHash}`,
    },
    body: JSON.stringify({
      prompt,
      settlementTxHash,
      payerAddress,
      lang,
    }),
  })

  const bodyText = await res.text()
  let parsed: unknown
  try {
    parsed = JSON.parse(bodyText)
  } catch {
    throw new Error(`forge-agent returned non-JSON (${res.status}): ${bodyText.slice(0, 200)}`)
  }

  if (!res.ok) {
    const err = parsed as { error?: string }
    throw new Error(`forge-agent ${res.status}: ${err?.error ?? bodyText.slice(0, 200)}`)
  }

  const body = parsed as { success?: boolean }
  if (!body.success) {
    const err = parsed as { error?: string }
    throw new Error(`forge-agent returned success:false — ${err?.error ?? "unknown"}`)
  }

  return parsed as ForgeAgentSuccessBody
}

// ---------------------------------------------------------------------------
// Request for the initial 402 challenge
// ---------------------------------------------------------------------------

async function fetchX402Challenge(
  origin: string,
  prompt: string,
  lang: "en" | "es",
): Promise<X402Challenge> {
  const forgeUrl = `${origin}/api/forge-agent`
  const res = await fetch(forgeUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, lang }),
  })

  if (res.status !== 402) {
    // If the server skipped the 402 gate (e.g. payment already satisfied),
    // this is unexpected for the agent flow.
    const text = await res.text()
    throw new Error(
      `Expected 402 from forge-agent, got ${res.status}. Body: ${text.slice(0, 200)}`,
    )
  }

  const body = (await res.json()) as ForgeAgentPaymentRequiredBody
  const challenge = extractChallengeFrom402(body)
  if (!challenge) {
    throw new Error("forge-agent 402 response did not include a valid x402 challenge object.")
  }
  return challenge
}

// ---------------------------------------------------------------------------
// POST handler
// ---------------------------------------------------------------------------

export async function POST(request: NextRequest): Promise<NextResponse<AgentForgeResponse>> {
  // 1. Auth check
  const authHeader = request.headers.get("authorization")
  if (!verifyBearerToken(authHeader)) {
    return NextResponse.json(
      { success: false, error: "Unauthorized. Provide a valid Authorization: Bearer <AGENT_API_KEY> header." },
      { status: 401 },
    )
  }

  // 2. Agent keypair check
  const secretKey = agentStellarSecretKey()
  if (!secretKey) {
    return NextResponse.json(
      {
        success: false,
        error:
          "AGENT_STELLAR_SECRET_KEY is not configured on this server. " +
          "Set it in .env.local and restart to enable autonomous agent payments.",
      },
      { status: 503 },
    )
  }

  // 3. Parse body
  let body: AgentForgeBody
  try {
    body = (await request.json()) as AgentForgeBody
  } catch {
    return NextResponse.json({ success: false, error: "Invalid JSON body." }, { status: 400 })
  }

  const prompt = body.prompt?.trim()
  if (!prompt) {
    return NextResponse.json(
      { success: false, error: "Missing required field: prompt (string)." },
      { status: 400 },
    )
  }

  let agentKeypair: Keypair
  try {
    agentKeypair = Keypair.fromSecret(secretKey)
  } catch {
    return NextResponse.json(
      { success: false, error: "AGENT_STELLAR_SECRET_KEY is not a valid Stellar secret key (S…)." },
      { status: 503 },
    )
  }

  const agentPublicKey = agentKeypair.publicKey()
  const payerAddress = body.payerAddress?.trim() || agentPublicKey
  const origin = request.nextUrl.origin
  const outputLang = normalizeAgentForgeLang(body.lang)

  // 4. Fetch the 402 payment challenge from /api/forge-agent
  let challenge: X402Challenge
  try {
    challenge = await fetchX402Challenge(origin, prompt, outputLang)
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    console.error("[agent/forge] Failed to fetch x402 challenge:", msg)
    return NextResponse.json(
      { success: false, error: "Failed to obtain x402 challenge.", detail: msg },
      { status: 502 },
    )
  }

  // Override challenge amount with REQUIRED_AMOUNT from env if it looks more reliable.
  const requiredAmount = parseInt(REQUIRED_AMOUNT, 10)
  if (Number.isFinite(requiredAmount) && requiredAmount > 0) {
    challenge.amount = requiredAmount
  }

  // 5. Sign + submit the settle transaction with the agent keypair
  let settlementTxHash: string
  try {
    const result = await settleX402Challenge(challenge, agentKeypair, payerAddress)
    settlementTxHash = result.txHash
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    console.error("[agent/forge] settle transaction failed:", msg)
    return NextResponse.json(
      { success: false, error: "Agent payment (settle) failed.", detail: msg },
      { status: 502 },
    )
  }

  console.log(
    `[agent/forge] Payment confirmed. payer=${agentPublicKey} txHash=${settlementTxHash}`,
  )

  // 6. Re-call forge-agent with the settlement proof
  let forgeResult: ForgeAgentSuccessBody
  try {
    forgeResult = await callForgeAgentWithProof(origin, prompt, settlementTxHash, payerAddress, outputLang)
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    console.error("[agent/forge] forge-agent generation failed after payment:", msg)
    return NextResponse.json(
      {
        success: false,
        error: "Payment was confirmed on-chain but AI generation failed. Check server logs.",
        detail: msg,
      },
      { status: 500 },
    )
  }

  const imageUrl = forgeResult.imageUrl ?? forgeResult.image_url ?? ""
  const lore = forgeResult.lore ?? ""

  // 7. Upload image to IPFS (best-effort)
  const ipfsCid = await uploadImageToIpfs(imageUrl)

  const amountPaid = `${stroopsToLiqDisplay(String(challenge.amount))} ${PHASER_LIQ_SYMBOL}`

  return NextResponse.json({
    success: true,
    payer: agentPublicKey,
    amountPaid,
    txHash: settlementTxHash,
    imageUrl,
    lore,
    ipfsCid,
    tokenId: null,
    collectionId: 0,
  })
}
